# Main Application Configuration
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/leave_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
  
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: ${HIBERNATE_FORMAT_SQL:false}
  
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}
    validate-on-migrate: ${FLYWAY_VALIDATE_ON_MIGRATE:true}

  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:10MB}

  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    debug: ${MAIL_DEBUG:false}

server:
  port: ${SERVER_PORT:8082}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:leave-service}
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: ${HEALTH_SHOW_DETAILS:always}

logging:
  level:
    com.daking.leave: ${LOG_LEVEL_APP:INFO}
    org.springframework.security: ${LOG_LEVEL_SECURITY:INFO}
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE:INFO}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_LEVEL_HIBERNATE_BINDER:INFO}
    org.springframework.web: ${LOG_LEVEL_WEB:INFO}
    org.springframework.boot.actuator: ${LOG_LEVEL_ACTUATOR:INFO}
    org.springframework.boot.autoconfigure: ${LOG_LEVEL_AUTOCONFIG:INFO}
    org.springframework.context: ${LOG_LEVEL_CONTEXT:INFO}
    org.springframework.cloud.netflix.eureka: ${LOG_LEVEL_EUREKA:INFO}
    root: ${LOG_LEVEL_ROOT:INFO}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://frontend:80}
    allowed-methods: ${CORS_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
    allowed-headers: ${CORS_ALLOWED_HEADERS:*}
    allow-credentials: ${CORS_ALLOW_CREDENTIALS:true}
    max-age: ${CORS_MAX_AGE:3600}

jwt:
  secret: ${JWT_SECRET:default-secret-key}
  expiration: ${JWT_EXPIRATION:86400000}

# Feign Client Configuration
feign:
  client:
    config:
      default:
        connect-timeout: ${FEIGN_CONNECT_TIMEOUT:5000}
        read-timeout: ${FEIGN_READ_TIMEOUT:5000}
        logger-level: ${FEIGN_LOGGER_LEVEL:basic}
  compression:
    request:
      enabled: ${FEIGN_COMPRESSION_REQUEST:true}
    response:
      enabled: ${FEIGN_COMPRESSION_RESPONSE:true}
  hystrix:
    enabled: ${FEIGN_HYSTRIX_ENABLED:false}
  circuitbreaker:
    enabled: ${FEIGN_CIRCUIT_BREAKER_ENABLED:false} 