# Development Profile Configuration
spring:
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create-drop
  mail:
    debug: true

logging:
  level:
    com.daking.leave: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG

management:
  endpoint:
    health:
      show-details: always

app:
  cors:
    allowed-origins: http://localhost:3000,http://localhost:5713,http://localhost:8080 