# Docker Profile Configuration
spring:
  jpa:
    show-sql: false
    hibernate:
      format_sql: false
      ddl-auto: update
  mail:
    debug: false

logging:
  level:
    com.daking.auth: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.springframework.web: INFO
    root: INFO

management:
  endpoint:
    health:
      show-details: always

# Docker-specific settings
eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:auth-service}
    prefer-ip-address: true

# Docker environment settings
app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://frontend:80} 