spring:
  application:
    name: eureka-server
  security:
    user:
      name: ${EUREKA_DASHBOARD_USER:eureka}
      password: ${EUREKA_DASHBOARD_PASSWORD:eureka123}

server:
  port: ${SERVER_PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_DASHBOARD_USER:eureka}:${EUREKA_DASHBOARD_PASSWORD:eureka123}@${EUREKA_INSTANCE_HOSTNAME:localhost}:${SERVER_PORT:8761}/eureka/
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always 